### ISSUE TITLE
Passenger not working?

### ISSUE THREAD

**Issue by raptorbalaji** [javereec/spree-demo-passenger-docker#1]
Thank you for the great job. I have cloned the code base and followed the instructions. When I hit port 80, I'm getting an nginx welcome page instead of spree site. Can you please help?

**Comment by javereec** [comment]
This is an old test of mine. I'm guessing that it listens to `www.webapp.com`. If you are using osx, you can change your `etc/hosts` file with an entry (change ip address so you can reach the container)

ip.ad.re.ss www.webapp.com

After that I guess it should work.

**Comment by raptorbalaji** [comment]
Thank you, Jan. Will try it out.
